### ISSUE TITLE
wont start

### ISSUE THREAD

**Issue by benbenlaw** [lorddusk/HQM#514] opened 2020-10-10 16:38 UTC
[crash-2020-10-10_17.37.32-fml.txt](https://github.com/lorddusk/HQM/files/5359431/crash-2020-10-10_17.37.32-fml.txt)

**Comment by lorddusk** [comment] 2020-10-10 16:40
This... Is not a bug report.
Please give more information.

**Comment by benbenlaw** [comment] 2020-10-10 16:42
game will not start says there a problem with hqm

**Comment by benbenlaw** [comment] 2020-10-10 16:53
turn out after quests saved the game doesnt load?

**Comment by benbenlaw** [comment] 2020-10-10 16:54
in config/hqm/default/set removeing quest line from there makes the game load again

**Comment by shedaniel** [comment] 2020-10-10 17:24
Can you send the json of the quest line?

**Comment by shedaniel** [comment] 2020-10-10 17:34
Should be fixed in 5.5.1, please reopen the issue if it remains unfixed.

**Closed as completed** 2020-10-10 17:34 UTC
Labels: bug

**Comment by benbenlaw** [comment] 2020-10-11 14:41
can confirm is now working thanks for the update
