### ISSUE TITLE
World Crashes on Closing Quest book

### ISSUE THREAD

**Issue by Cuplex17** [lorddusk/HQM#375] opened 2017-12-07 06:01 UTC
I was editing some quests and closing the quest book to check something in JEI when the world crashes and puts me back to the main menu. 
[2017-12-07-4.log.gz](https://github.com/lorddusk/HQM/files/1537969/2017-12-07-4.log.gz)

Edit: After I removed an empty quest, closing the quest book now makes the whole game not respond.

**Comment by canitzp** [comment] 2017-12-07 06:19
There is nothing is this log file. Can you post another log file please? In its name there should be 'fml-client latest' or 'fml-server latest'

**Comment by Cuplex17** [comment] 2017-12-07 06:23
Do you mean "latest.log"?

**Comment by canitzp** [comment] 2017-12-07 06:25
Here is a picture, how it should look like: http://puu.sh/yB67F/456f6e682b.png
Here I would need the second file

**Comment by Cuplex17** [comment] 2017-12-07 06:32
Internet kind of slow right now. Can I do a pastebin?

**Comment by canitzp** [comment] 2017-12-07 06:33
Yeah do it

**Comment by Cuplex17** [comment] 2017-12-07 06:34
Actually, paste too big, pastebin won't allow. Please wait for me to upload file directly.

**Comment by Cuplex17** [comment] 2017-12-07 06:36
[latest.log](https://github.com/lorddusk/HQM/files/1538017/latest.log)

**Comment by canitzp** [comment] 2017-12-07 07:53
The latest.log is also not enough. I could find an avidence that your problem is caused by HQM in both log files. You can try to delete the config folder of HQM, after backuping it and load the world

**Comment by Cuplex17** [comment] 2017-12-07 08:01
For backing up, should i just copy the world save folder onto desktop and delete the old one? Do I need to do anything else apart from that?

**Comment by canitzp** [comment] 2017-12-07 08:05
You just copy /config/hqm to any other folder and then delete the nonbackup /config/hqm

**Comment by Cuplex17** [comment] 2017-12-07 08:11
Ok let me try that and see if it fixes the problem.

**Comment by Cuplex17** [comment] 2017-12-07 08:18
No, it still crashes the game when I close the quest book.

**Comment by canitzp** [comment] 2017-12-07 10:01
Then it is another mod. What is the exact message you get when the world closes?

**Comment by Cuplex17** [comment] 2017-12-08 00:09
It just says internal server closed and puts me onto the multiplayer menu screen.

**Comment by canitzp** [comment] 2017-12-08 03:28
Then you have to do it the old way. Removing one mod, try the world. If it works than fine, otherwise remive the next one. I'll close this for now. If you find out that it is a bug with HQM than just reopen this issue

**Closed as completed** 2017-12-08 03:28 UTC
