### ISSUE TITLE
Cannot Open Quest Book

### ISSUE THREAD

**Issue by Thornstromb** [lorddusk/HQM#180] opened 2016-04-10 21:00 UTC
***\* EDIT MODE IS OFF ON BOTH SERVER AND CLIENT ****
just updated server files and game, NOBODY ELSE ON SERVER is getting this issue.
upon trying to open the quest book, nothing happens, no crash, no quest gui, nothing
nothing except THIS in the log.

https://gist.github.com/Thornstromb/889a83da7fc63bfdb83060fea29d8b91

(Sorry for not remembering about pastebins)

**Comment by way2muchnoise** [comment] 2016-04-10 21:02
@Thornstromb Execpt this log should have been on a paste service see https://github.com/lorddusk/HQM/blob/1.8/CONTRIBUTING.md#list-of-paste-services

**Comment by Thornstromb** [comment] 2016-04-10 22:15
Addition:
book opens fine in single player with no issue, and resetting the quest data via deletion of HardcoreQuesting folder in world folder then re-enabling of HQM via ingame command did NOT FIX ISSUE

**Comment by lorddusk** [comment] 2016-04-10 22:16
Could you please upload your fml-log?

**Comment by Thornstromb** [comment] 2016-04-10 22:17
FML?

**Comment by lorddusk** [comment] 2016-04-10 22:17
Yes, it's in the logs folder of your minecraft instance...

**Comment by Thornstromb** [comment] 2016-04-10 22:18
k one sec while i regen the entire log system with nothing but game start, call errror, logout
EDIT: would you need the Serverside FML?

**Comment by Thornstromb** [comment] 2016-04-10 22:35
Clientside FML here https://gist.github.com/Thornstromb/a25df989c3939fc515a9b880cd7a9cde
sidenote: serverside FML is not truly available (hes not willing to restart the server AGAIN just to generate another logfile) but previous issuance of the serverside fml log has been perused, to no avail (no hqm-connected error messages located, just like how the standard log sees absolutely nothing serverside as well.)

**Comment by cjm721** [comment] 2016-04-11 00:18
Looks to be a duplicate of #174

**Comment by Thornstromb** [comment] 2016-04-11 02:57
forgot to mention: player.dats are all around 4 kb, NOT anywhere close to the 500kb overflow level

**Comment by Thornstromb** [comment] 2016-04-11 04:02
NEW INFORMATION: upon running a copy of my friends (server-hosts) MC folder, the problem has vanished. im assuming this means the problem is in the configs somehow
UPDATE: replacing my curse Config folder with the larger folder my buddy had seems to have fixed it as well

**Comment by way2muchnoise** [comment] 2016-06-02 09:19
Closed due to no longer supporting 1.7.10, please check if this problem persists in the latest 1.9.4 version. Most of the saving, loading and networking is rewritten in the new versions. Make a new issue if the crash returns

**Closed as completed by way2muchnoise** 2016-06-02 09:19 UTC
