### ISSUE TITLE
[Suggestion] Energy Consumption Task

### ISSUE THREAD

**Issue by CodexAdrian** [lorddusk/HQM#664] opened 2022-08-24 20:35 UTC
Pretty straightforward, right now there's no way to submit energy as a task, A new kind of consumption task that just takes in energy would be great, with integration with TechReborn's Energy API on fabric for mod compatibility

(If you like this idea, I will submit a PR with this implemented)

**Comment by kirderf1** [comment] 2022-08-24 21:55
Duplicate of #294. This seems like a very appropriate task type to add.

**Comment by canitzp** [comment] 2023-08-23 12:00
Since this is a duplicate, I'll close it. @CodexAdrian Feeld free to open a pr with the new task

**Closed as completed by canitzp** 2023-08-23 12:00 UTC
Labels: duplicate
