### ISSUE TITLE
Quest Not Showing on Server 

### ISSUE THREAD

**Issue by CluelessPhil** [lorddusk/HQM#266] opened 2017-02-04 19:28 UTC
Hello, so I've created a modpack and it uses Hardcore Questing Mode and the quests work fine they show up on single player. But once i created a server for it (having HQM installed the the Quest files in the config) the quest didn't show up and neither did the description. So i tried to enable hardcore mode and it said it was enabled but I opened the book and it didn't show the hearts. So i tried one last thing ServerSync and that didn't work when i enabled it from the config. Can someone help me?

**Comment by canitzp** [comment] 2017-02-04 20:02
duplicate of #249

**Closed as completed** 2017-02-04 21:13 UTC
Labels: duplicate
